services:
  - type: web
    name: rolexai-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: GROQ_API_KEY
        value: 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
      - key: PORT
        value: 5001
